# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='date',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='charge',
            name='value',
            field=models.FloatField(),
        ),
    ]
