# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20161014_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AddField(
            model_name='account',
            name='account_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='account',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='charge', to='finance.Account'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='charge_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='charge',
            name='value',
            field=models.FloatField(blank=True),
        ),
    ]
