# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20161111_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='charge_id',
        ),
        migrations.AddField(
            model_name='account',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charge',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='charge',
            name='value',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
