# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20161111_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='charge',
            name='charge_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
