# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20161111_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='finance.Account'),
        ),
    ]
