# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20161111_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(default='-@-.ru', max_length=70),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
